---
resources:
  - name: repo
    type: git
    source:
      uri: {{repo-url}}
      branch: master

  - name: cf-deploy
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: test
    plan:
      - get: repo
        trigger: true
      - aggregate:
        - task: test
          file: repo/ci/tasks/test.yml
          params:
            PROJECT_NAME: NotesApp.Tests
        - task: integration-test
          file: repo/ci/tasks/test.yml
          params:
            PROJECT_NAME: NotesApp.IntegrationTests

  - name: build-deploy
    serial_groups: [deploy]
    plan:
      - get: repo
        trigger: true
        passed: [test]
      - task: build
        file: repo/ci/tasks/build.yml
        params:
          PROJECT_NAME: NotesApp
      - put: cf-deploy
        params:
          manifest: repo/ci/manifest.yml
          path: published

  - name: smoke-test
    serial_groups: [deploy]
    plan:
      - get: repo
        passed: [build-deploy]
      - get: cf-deploy
        trigger: true
        passed: [build-deploy]
      - task: newman-test
        file: repo/ci/tasks/newman-test.yml
        params:
          COLLECTION_URL: repo/ci/newman/NotesApp.postman_collection.json
          ENVIRONMENT_URL: repo/ci/newman/NotesApp.postman_environment.json